import type {
  Application,
  AppNotification,
  AppointmentSlot,
  AppUser,
  AuditLogEntry,
  Certificate,
  Inspection,
  Instrument,
} from "./types"

export const DOCUMENT_TEMPLATE = [
  { key: "ownership", label: "Proof of Ownership" },
  { key: "manufacturer", label: "Purchase / Manufacturer Document" },
  { key: "previousCert", label: "Previous Certificate (if any)" },
  { key: "identification", label: "Identification Document" },
]

export const INSTRUMENT_TYPES = ["Weighing Scale", "Electronic Balance", "Platform Scale", "Measuring Instrument"] as const

export const seedUsers: AppUser[] = [
  {
    id: "u-applicant-1",
    name: "Lakshya Traders",
    email: "contact@lakshyatraders.in",
    mobile: "+91 98100 22456",
    role: "applicant",
    createdAt: "2026-08-01",
  },
  {
    id: "u-officer-1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@metrology.gov.in",
    mobile: "+91 98110 33567",
    role: "officer",
    title: "Verification Officer",
    createdAt: "2024-03-11",
  },
  {
    id: "u-officer-2",
    name: "Sunita Sharma",
    email: "sunita.sharma@metrology.gov.in",
    mobile: "+91 98120 44678",
    role: "officer",
    title: "Verification Officer",
    createdAt: "2023-07-22",
  },
  {
    id: "u-admin-1",
    name: "Anil Deshmukh",
    email: "anil.deshmukh@metrology.gov.in",
    mobile: "+91 98130 55789",
    role: "admin",
    title: "System Administrator",
    createdAt: "2022-01-14",
  },
]

export const seedAppointmentSlots: AppointmentSlot[] = [
  { id: "slot-1", date: "2026-09-15", time: "09:00 AM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: true, applicationId: "APP-2026-00118" },
  { id: "slot-2", date: "2026-09-15", time: "11:00 AM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: true, applicationId: "APP-2026-00124" },
  { id: "slot-3", date: "2026-09-15", time: "02:00 PM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-4", date: "2026-09-16", time: "09:30 AM", officer: "Sunita Sharma", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-5", date: "2026-09-16", time: "11:30 AM", officer: "Sunita Sharma", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-6", date: "2026-09-16", time: "03:00 PM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-7", date: "2026-09-17", time: "10:00 AM", officer: "Sunita Sharma", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-8", date: "2026-09-17", time: "01:00 PM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-9", date: "2026-09-18", time: "09:00 AM", officer: "Sunita Sharma", location: "Legal Metrology Verification Office, Sector 12", booked: false },
  { id: "slot-10", date: "2026-09-18", time: "12:00 PM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12", booked: false },
]

const uploadedDocs = () => DOCUMENT_TEMPLATE.map((d) => ({ ...d, uploaded: true, fileName: `${d.key}.pdf` }))

export const seedApplications: Application[] = [
  {
    id: "APP-2026-00101",
    applicantId: "u-applicant-1",
    applicantName: "Lakshya Traders",
    mobile: "+91 98100 22456",
    email: "contact@lakshyatraders.in",
    address: "12-A, Industrial Estate, Sector 18, Gurugram, Haryana",
    instrument: {
      type: "Weighing Scale",
      manufacturer: "XYZ Instruments Pvt. Ltd.",
      model: "DWS-500",
      serialNumber: "DWS-78421",
      capacity: "500 kg",
      locationOfUse: "Wholesale Grain Market, Gurugram",
    },
    documents: uploadedDocs(),
    status: "Approved",
    appointment: { slotId: "slot-old-1", date: "2026-08-10", time: "10:00 AM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12" },
    certificateId: "CERT-2026-00871",
    inspectionId: "INS-00871",
    instrumentId: "INST-1001",
    createdAt: "2026-08-01",
  },
  {
    id: "APP-2026-00109",
    applicantId: "u-applicant-2",
    applicantName: "Sharma Kirana Store",
    mobile: "+91 98140 66890",
    email: "sharmakirana@example.com",
    address: "44, Main Bazaar, Karnal, Haryana",
    instrument: {
      type: "Electronic Balance",
      manufacturer: "Precision Weigh Co.",
      model: "EB-200",
      serialNumber: "EB-20981",
      capacity: "200 kg",
      locationOfUse: "Retail Store, Karnal",
    },
    documents: uploadedDocs(),
    status: "Rejected",
    appointment: { slotId: "slot-old-2", date: "2026-08-20", time: "11:30 AM", officer: "Sunita Sharma", location: "Legal Metrology Verification Office, Sector 12" },
    inspectionId: "INS-00879",
    createdAt: "2026-08-05",
  },
  {
    id: "APP-2026-00118",
    applicantId: "u-applicant-3",
    applicantName: "Verma Agro Traders",
    mobile: "+91 98150 77901",
    email: "vermaagro@example.com",
    address: "Plot 9, Grain Market Road, Panipat, Haryana",
    instrument: {
      type: "Platform Scale",
      manufacturer: "Accura Scales Ltd.",
      model: "PS-1000",
      serialNumber: "PS-55210",
      capacity: "1000 kg",
      locationOfUse: "Grain Market, Panipat",
    },
    documents: uploadedDocs(),
    status: "Inspection Scheduled",
    appointment: { slotId: "slot-1", date: "2026-09-15", time: "09:00 AM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12" },
    createdAt: "2026-09-01",
  },
  {
    id: "APP-2026-00124",
    applicantId: "u-applicant-1",
    applicantName: "Lakshya Traders",
    mobile: "+91 98100 22456",
    email: "contact@lakshyatraders.in",
    address: "12-A, Industrial Estate, Sector 18, Gurugram, Haryana",
    instrument: {
      type: "Weighing Scale",
      manufacturer: "XYZ Instruments Pvt. Ltd.",
      model: "DWS-500",
      serialNumber: "DWS-78433",
      capacity: "500 kg",
      locationOfUse: "Wholesale Grain Market, Gurugram",
    },
    documents: uploadedDocs(),
    status: "Inspection Scheduled",
    appointment: { slotId: "slot-2", date: "2026-09-15", time: "11:00 AM", officer: "Rajesh Kumar", location: "Legal Metrology Verification Office, Sector 12" },
    createdAt: "2026-09-05",
  },
  {
    id: "APP-2026-00131",
    applicantId: "u-applicant-4",
    applicantName: "Gupta Provision Store",
    mobile: "+91 98160 88012",
    email: "guptaprovision@example.com",
    address: "22, Old Market, Ambala, Haryana",
    instrument: {
      type: "Measuring Instrument",
      manufacturer: "MeasureTech India",
      model: "MT-Flow-30",
      serialNumber: "MT-30117",
      capacity: "30 L/min",
      locationOfUse: "Fuel Retail Outlet, Ambala",
    },
    documents: DOCUMENT_TEMPLATE.map((d, i) => ({ ...d, uploaded: i < 3, fileName: i < 3 ? `${d.key}.pdf` : undefined })),
    status: "Under Review",
    createdAt: "2026-09-06",
  },
  {
    id: "APP-2026-00133",
    applicantId: "u-applicant-5",
    applicantName: "New Bharat Wholesalers",
    mobile: "+91 98170 99123",
    email: "newbharat@example.com",
    address: "8, Transport Nagar, Hisar, Haryana",
    instrument: {
      type: "Weighing Scale",
      manufacturer: "XYZ Instruments Pvt. Ltd.",
      model: "DWS-750",
      serialNumber: "DWS-91004",
      capacity: "750 kg",
      locationOfUse: "Wholesale Market, Hisar",
    },
    documents: uploadedDocs(),
    status: "Pending",
    createdAt: "2026-09-07",
  },
]

export const seedInspections: Inspection[] = [
  {
    id: "INS-00871",
    applicationId: "APP-2026-00101",
    officer: "Rajesh Kumar",
    observations: {
      condition: "Good",
      display: "Pass",
      seal: "Valid",
      accuracy: "Within permissible limit",
      identification: "Verified",
    },
    remarks: "Instrument found in good physical condition. Accuracy is within permissible limits.",
    result: "PASS",
    date: "2026-08-10",
  },
  {
    id: "INS-00879",
    applicationId: "APP-2026-00109",
    officer: "Sunita Sharma",
    observations: {
      condition: "Damaged",
      display: "Fail",
      seal: "Invalid",
      accuracy: "Outside permissible limit",
      identification: "Verified",
    },
    remarks: "Display unit malfunctioning and accuracy readings fall outside permissible tolerance. Seal found broken.",
    result: "FAIL",
    date: "2026-08-20",
  },
]

export const seedCertificates: Certificate[] = [
  {
    id: "CERT-2026-00871",
    applicationId: "APP-2026-00101",
    certificateNumber: "CERT-2026-00871",
    qrToken: "MV-QR-00871",
    applicantName: "Lakshya Traders",
    instrument: {
      type: "Weighing Scale",
      manufacturer: "XYZ Instruments Pvt. Ltd.",
      model: "DWS-500",
      serialNumber: "DWS-78421",
      capacity: "500 kg",
      locationOfUse: "Wholesale Grain Market, Gurugram",
    },
    officer: "Rajesh Kumar",
    issueDate: "2026-08-10",
    validUntil: "2027-08-10",
    status: "Valid",
  },
  {
    id: "CERT-2025-00612",
    applicationId: "APP-2025-00612",
    certificateNumber: "CERT-2025-00612",
    qrToken: "MV-QR-00612",
    applicantName: "Om Traders",
    instrument: {
      type: "Electronic Balance",
      manufacturer: "Precision Weigh Co.",
      model: "EB-150",
      serialNumber: "EB-14032",
      capacity: "150 kg",
      locationOfUse: "Retail Store, Rohtak",
    },
    officer: "Sunita Sharma",
    issueDate: "2025-06-01",
    validUntil: "2026-06-01",
    status: "Expired",
  },
]

export const seedInstruments: Instrument[] = [
  {
    id: "INST-1001",
    serialNumber: "DWS-78421",
    type: "Weighing Scale",
    manufacturer: "XYZ Instruments Pvt. Ltd.",
    model: "DWS-500",
    owner: "Lakshya Traders",
    ownerId: "u-applicant-1",
    status: "Valid",
    lastVerification: "2026-08-10",
    validUntil: "2027-08-10",
    applicationId: "APP-2026-00101",
    certificateId: "CERT-2026-00871",
  },
  {
    id: "INST-1002",
    serialNumber: "EB-14032",
    type: "Electronic Balance",
    manufacturer: "Precision Weigh Co.",
    model: "EB-150",
    owner: "Om Traders",
    ownerId: "u-applicant-6",
    status: "Expired",
    lastVerification: "2025-06-01",
    validUntil: "2026-06-01",
    certificateId: "CERT-2025-00612",
  },
  {
    id: "INST-1003",
    serialNumber: "PS-40112",
    type: "Platform Scale",
    manufacturer: "Accura Scales Ltd.",
    model: "PS-800",
    owner: "Bansal Traders",
    ownerId: "u-applicant-7",
    status: "Expiring Soon",
    lastVerification: "2025-10-02",
    validUntil: "2026-10-02",
  },
  {
    id: "INST-1004",
    serialNumber: "MT-22056",
    type: "Measuring Instrument",
    manufacturer: "MeasureTech India",
    model: "MT-Flow-20",
    owner: "Highway Fuel Point",
    ownerId: "u-applicant-8",
    status: "Valid",
    lastVerification: "2026-04-18",
    validUntil: "2027-04-18",
  },
  {
    id: "INST-1005",
    serialNumber: "EB-20981",
    type: "Electronic Balance",
    manufacturer: "Precision Weigh Co.",
    model: "EB-200",
    owner: "Sharma Kirana Store",
    ownerId: "u-applicant-2",
    status: "Under Verification",
    applicationId: "APP-2026-00109",
  },
  {
    id: "INST-1006",
    serialNumber: "PS-55210",
    type: "Platform Scale",
    manufacturer: "Accura Scales Ltd.",
    model: "PS-1000",
    owner: "Verma Agro Traders",
    ownerId: "u-applicant-3",
    status: "Under Verification",
    applicationId: "APP-2026-00118",
  },
  {
    id: "INST-1007",
    serialNumber: "DWS-60310",
    type: "Weighing Scale",
    manufacturer: "XYZ Instruments Pvt. Ltd.",
    model: "DWS-400",
    owner: "City Grain Depot",
    ownerId: "u-applicant-9",
    status: "Expiring Soon",
    lastVerification: "2025-09-28",
    validUntil: "2026-09-28",
  },
  {
    id: "INST-1008",
    serialNumber: "MT-30117",
    type: "Measuring Instrument",
    manufacturer: "MeasureTech India",
    model: "MT-Flow-30",
    owner: "Gupta Provision Store",
    ownerId: "u-applicant-4",
    status: "Under Verification",
    applicationId: "APP-2026-00131",
  },
]

export const seedNotifications: AppNotification[] = [
  {
    id: "NOTIF-1",
    audience: "applicant",
    userId: "u-applicant-1",
    title: "Certificate expiring soon",
    message: "Certificate CERT-2026-00871 will expire in 30 days. Renew verification to stay compliant.",
    date: "2026-09-08",
    read: false,
    type: "warning",
  },
  {
    id: "NOTIF-2",
    audience: "applicant",
    userId: "u-applicant-1",
    title: "Appointment confirmed",
    message: "Inspection appointment confirmed for 15 September 2026, 11:00 AM at Legal Metrology Verification Office.",
    date: "2026-09-05",
    read: false,
    type: "info",
  },
  {
    id: "NOTIF-3",
    audience: "applicant",
    userId: "u-applicant-1",
    title: "Application approved",
    message: "Application APP-2026-00101 has been approved and a certificate has been issued.",
    date: "2026-08-10",
    read: true,
    type: "success",
  },
  {
    id: "NOTIF-4",
    audience: "officer",
    title: "New application submitted",
    message: "A new verification application has been submitted and is awaiting review.",
    date: "2026-09-07",
    read: false,
    type: "info",
  },
  {
    id: "NOTIF-5",
    audience: "admin",
    title: "Certificates expiring this month",
    message: "3 certificates are due to expire within 30 days. Notify applicants for renewal.",
    date: "2026-09-01",
    read: false,
    type: "warning",
  },
]

export const seedAuditLog: AuditLogEntry[] = [
  {
    id: "AUD-1",
    user: "Lakshya Traders",
    role: "applicant",
    action: "Submitted application",
    reference: "APP-2026-00101",
    status: "Success",
    timestamp: "2026-08-01 10:14 AM",
  },
  {
    id: "AUD-2",
    user: "Rajesh Kumar",
    role: "officer",
    action: "Updated inspection result",
    reference: "APP-2026-00101",
    status: "Success",
    timestamp: "2026-08-10 12:32 PM",
  },
  {
    id: "AUD-3",
    user: "Rajesh Kumar",
    role: "officer",
    action: "Issued certificate",
    reference: "CERT-2026-00871",
    status: "Success",
    timestamp: "2026-08-10 12:41 PM",
  },
  {
    id: "AUD-4",
    user: "Sunita Sharma",
    role: "officer",
    action: "Updated inspection result",
    reference: "APP-2026-00109",
    status: "Failed",
    timestamp: "2026-08-20 03:05 PM",
  },
  {
    id: "AUD-5",
    user: "Verma Agro Traders",
    role: "applicant",
    action: "Scheduled inspection appointment",
    reference: "APP-2026-00118",
    status: "Success",
    timestamp: "2026-09-01 09:47 AM",
  },
  {
    id: "AUD-6",
    user: "Anil Deshmukh",
    role: "admin",
    action: "Reviewed audit log",
    reference: "SYSTEM",
    status: "Info",
    timestamp: "2026-09-07 05:00 PM",
  },
]
